sudo: required
script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

env:
 - RUST_TOOLCHAIN=stable
 - RUST_TOOLCHAIN=beta
 - RUST_TOOLCHAIN=nightly

arch:
  packages:
    - qemu-headless
    - sudo
    - libsystemd
    - libinput
    - acl
    - udev
    - coreutils
    - hwids
#    - git (is a dev dependency but we already have the repo)
    - rpmextract
    - curl
    - libarchive
    - rustup
    - mono
    - cdrkit
  script:
    - rustup default "$RUST_TOOLCHAIN"
    - export PATH=$HOME/.cargo/bin:$PATH
    - make all test
    - if [ "$RUST_TOOLCHAIN" = "nightly" ]; then make clippy; fi

matrix:
  fast_finish: true
  allow_failures:
    - env: RUST_TOOLCHAIN=nightly
