language: csharp
mono: latest
dist: trusty
env:
 - RUST_TOOLCHAIN=stable
 - RUST_TOOLCHAIN=beta
 - RUST_TOOLCHAIN=nightly
install:
 - curl -sSf https://sh.rustup.rs | sh -s -- --default-toolchain=$RUST_TOOLCHAIN -y
 - export PATH=$HOME/.cargo/bin:$PATH
 - if [ "$RUST_TOOLCHAIN" = "nightly" ]; then cargo install clippy; fi
script: if [ "$RUST_TOOLCHAIN" = "nightly" ]; then make all clippy test; else make all test; fi
addons:
  apt:
    sources:
    - sourceline: 'ppa:jonathonf/gtk3.18'
    packages:
    - rpm2cpio
    - genisoimage
    - bsdtar
    - libudev-dev
    - libdbus-1-dev
    - libinput-dev
matrix:
  fast_finish: true
  allow_failures:
    - env: RUST_TOOLCHAIN=nightly
