[workspace]
members = ["windows-gaming", "vfio-ubind", "windows-edge-grab"]

[replace]
"xcb:0.8.0" = { git = "https://github.com/main--/rust-xcb.git" }
"input:0.2.0" = { git = "https://github.com/rusty-desktop/input.rs.git" }
"tokio-io:0.1.2" = { path = "../tokio-io" }
