[package]
name = "qmpgen"
version = "0.1.0"
authors = ["oberien <jaro.fietz@gmx.de>"]
build = "build.rs"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
curl = "0.4.6"
inflections = "1.1"

[build-dependencies]
peg = "0.5.1"
