[package]
name = "x11-edge-grab"
version = "0.1.0"
authors = ["oberien <jaro.fietz@gmx.de>"]

[dependencies]
xdg = "^2.1"
xcb = "0.8"
byteorder = "1.1"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"